#!/bin/sh
#trap "set +x; sleep 5; set -x" DEBUG
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`


sed -i "s/numberOfSubdomains\s\+[[:digit:]]\+/numberOfSubdomains $1/g" system/decomposeParDict
sed -i "s/numberOfSubdomains\s\+[[:digit:]]\+/numberOfSubdomains $1/g" ../solid/system/decomposeParDict

runApplication -l log.blockMesh.solid blockMesh -case ../solid

cd ../solid

sed -i s/defaultFaces/internal/g constant/polyMesh/boundary
cd ../fluid
runApplication -l log.changeDictionary.solid changeDictionary -case ../solid
runApplication -l log.setSet.solid setSet -case ../solid -batch ../solid/setBatch
runApplication -l log.setToZones.solid setsToZones -case ../solid -noFlipMap

runApplication -l log.decomposePar.solid decomposePar -case ../solid -cellDist

runApplication blockMesh
runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap

runApplication decomposePar -cellDist

cd ..

# Build hronTurekReport function object
wmake libso hronTurekReport

#./makeLinks fluid solid

#cd fluid

#runParallel $application $1

# ----------------------------------------------------------------- end-of-file
